-- Migration: 010_thumbnails.sql
-- Purpose: Add thumbnail_path column to documents table for E5 thumbnail persistence
-- Upgrade: Adds thumbnail_path to documents for storing relative path to generated thumbnails
-- Downgrade: ALTER TABLE DROP COLUMN thumbnail_path
-- Live DB Safety: Adding a nullable column with a default is a fast metadata-only operation in modern PostgreSQL
--
-- E5: Thumbnail Persistence
-- Thumbnails are generated by the ThumbnailGenerator worker and stored on disk in .thumbnails/
-- The relative path is stored here for retrieval via the /thumbnails/ API endpoint

ALTER TABLE documents ADD COLUMN IF NOT EXISTS thumbnail_path VARCHAR(500);

-- Index for quick lookup of documents with thumbnails
CREATE INDEX IF NOT EXISTS idx_documents_thumbnail_path ON documents(thumbnail_path) WHERE thumbnail_path IS NOT NULL;

-- Comment documentation
COMMENT ON COLUMN documents.thumbnail_path IS 'Relative path to generated thumbnail (e.g., ".thumbnails/1017_IMG_001_thumb.jpg"). NULL until thumbnail is generated.';

-- Record migration
INSERT INTO schema_migrations (migration_name) VALUES ('010_thumbnails.sql')
ON CONFLICT (migration_name) DO NOTHING;
